exclude: ['bower_components','node_modules','CNAME','bower.json','package.json','Gemgile','Gemgile.lock']
# Site settings
title: Carlos Fernandes
email: carlos@cfdev.com.br
description: > # this means to ignore newlines until "baseurl:"
  Teste
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cfdev.com" # the base hostname & protocol for your site
twitter_username: cafweb
github_username:  cafweb

# Build settings
markdown: kramdown

#sass:
#  sass_dir: _sass
#  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: [html, head, body]